apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: index-mosaic-
  namespace: argo
spec:
  entrypoint: workflow-entrypoint
  serviceAccountName: public-bucket-writer
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 600s
  podMetadata:
    labels:
      app: ls-geomad
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  nodeSelector:
    karpenter.sh/capacity-type: "spot" # Just to be explicit. In dep-terraform, the data-processing nodepool can only pick spot instances
    dep/workload: data-processing
  tolerations:
    - key: dep/workload
      operator: Equal
      value: data-processing
      effect: NoSchedule
  arguments:
    parameters:
      - name: image-name
        value: "ghcr.io/auspatious/ldn-lulc"
      - name: image-tag
        value: "latest"
      - name: dataset
        value: "all" # "all", "geomad", or "prediction"
      - name: region
        value: "all" # "all", "pacific", or "non-pacific"

  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: index-to-stac-geoparquet
            template: index-to-stac-geoparquet

          - name: make-mosaics
            depends: index-to-stac-geoparquet.Succeeded
            template: make-mosaics

    - name: index-to-stac-geoparquet
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 2Gi
            cpu: 1
        command: [ldn]
        args:
          - index-to-stac-geoparquet
          - --dataset
          - "{{ workflow.parameters.dataset }}"
          - --region
          - "{{ workflow.parameters.region }}"

    - name: make-mosaics
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 2Gi
            cpu: 1
        command: [ldn]
        args:
          - make-mosaics
          - --dataset
          - "{{ workflow.parameters.dataset }}"
          - --region
          - "{{ workflow.parameters.region }}"
