apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: landsat-geomad-
  namespace: argo
spec:
  entrypoint: workflow-entrypoint
  serviceAccountName: public-bucket-writer
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 600s
  parallelism: 50
  podMetadata:
    labels:
      app: ls-geomad
    annotations:
      karpenter.sh/do-not-disrupt: "true"
  nodeSelector:
    karpenter.sh/capacity-type: "spot" # Just to be explicit. In dep-terraform, the data-processing nodepool can only pick spot instances
    dep/workload: data-processing
  tolerations:
    - key: dep/workload
      operator: Equal
      value: data-processing
      effect: NoSchedule
  arguments:
    parameters:
      - name: version
        value: "0-2-0"
      - name: image-name
        value: "ghcr.io/auspatious/ldn-lulc"
      - name: image-tag
        value: "latest"
      - name: bucket
        value: "dep-public-staging"
      - name: region
        value: "pacific"
      - name: years
        # value: "2000-2025" # Which year(s) to process (e.g. "2000-2025" or "2000,2005,2010")
        value: "2025" # Just 2025 to test.
      - name: overwrite
        value: "--no-overwrite" # Can be "--overwrite" or "--no-overwrite"
      - name: decimated
        value: "--no-decimated" # Can be "--decimated" or "--no-decimated"
  templates:
    - name: workflow-entrypoint
      dag:
        tasks:
          - name: print-tasks
            template: print-tasks

          - name: filter-tasks
            depends: print-tasks.Succeeded
            template: filter-tasks
            arguments:
              parameters:
                - name: tasks-json
                  value: "{{ tasks.print-tasks.outputs.result }}"
                - name: overwrite
                  value: "{{ workflow.parameters.overwrite }}"

          - name: process-geomad
            depends: filter-tasks.Succeeded
            template: process-geomad
            arguments:
              parameters:
                - name: tile-id
                  value: "{{item.id}}"
                - name: year
                  value: "{{item.year}}"
                - name: region
                  value: "{{item.region}}"
            withParam: "{{ tasks.filter-tasks.outputs.result }}"

    - name: print-tasks
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            # Requesting a lot of resources for this simple task
            # This is a scheduling trick, if print-tasks requests small, karpenter would
            # provision a small node first (c6.xlarge/large), then process geomad can't fit
            #and has to wait for another node to come up. Not critical, just saves a few minutes
            # of waiting between tasks.
            memory: 18Gi
            cpu: 10
        command: [ldn]
        args:
          - print-tasks
          - --years
          - "{{ workflow.parameters.years }}"
          - --region
          - "{{ workflow.parameters.region }}"

    - name: filter-tasks
      inputs:
        parameters:
          - name: tasks-json
          - name: overwrite
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            # Same as print-tasks resources comment.
            memory: 18Gi
            cpu: 10
        command: [ldn]
        args:
          - filter-tasks
          - --tasks-json
          - "{{ inputs.parameters.tasks-json }}"
          - --version
          - "{{ workflow.parameters.version }}"
          - --bucket
          - "{{ workflow.parameters.bucket }}"
          - --dataset
          - "geomad"
          - "{{ inputs.parameters.overwrite }}"

    - name: process-geomad
      inputs:
        parameters:
          - name: tile-id
          - name: year
          - name: region
      # activeDeadlineSeconds: 900 # 15 minutes. Max time for a single try. Each retry pod will be killed after this time.
      retryStrategy:
        limit: "3"
        retryPolicy: OnFailure
        # backoff: # Not needed for this process. Retry immediately.
        #   maxDuration: "30m" # Max backoff wait time between retries, not total runtime.
        # # Don't retry OOMKills (137) because we don't scale up resources on retries.
        # When pod fails because <10 scenes are found code is 1. This would prevent retries of other errors too.
        expression: "asInt(lastRetry.exitCode) != 137 && asInt(lastRetry.exitCode) != 1"
      container:
        image: "{{ workflow.parameters.image-name }}:{{ workflow.parameters.image-tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            # Pod memory needed = (n_workers * memory_limit) + scheduler_overhead + main_process_overhead
            memory: 24Gi
            # Pod CPU needed = (n_workers * threads_per_worker) + scheduler_threads
            cpu: 14
          limits:
            memory: 32Gi
            cpu: 18
        command: [ldn]
        args:
          - geomad
          - --tile-id
          - "{{ inputs.parameters.tile-id }}"
          - --year
          - "{{ inputs.parameters.year }}"
          - --region
          - "{{ inputs.parameters.region }}"
          - --version
          - "{{ workflow.parameters.version }}"
          - --bucket
          - "{{ workflow.parameters.bucket }}"
          - --memory-limit
          - "12GB"
          - --n-workers
          - "2"
          - --threads-per-worker
          - "6"
          - --xy-chunk-size
          - "800"
          - "{{ workflow.parameters.overwrite }}"
          - "{{ workflow.parameters.decimated }}"
